<?php
/**
 *
 * @package    Material Dashboard Yii2
 * @author     CodersEden <hello@coderseden.com>
 * @link       https://www.coderseden.com
 * @copyright  2020 Material Dashboard Yii2 (https://www.coderseden.com)
 * @license    MIT - https://www.coderseden.com
 * @since      1.0
 */
namespace app\controllers;

use Yii;
use app\models\Subscribers;
use app\models\SubscribersSearch;
use app\models\Audit;
use app\components\AccessRule;
use yii\filters\VerbFilter;
use app\models\User;
use app\models\UserSearch;
use app\models\UserForm;
use yii\data\ArrayDataProvider;
use yii2tech\csvgrid\CsvGrid;


/**
 * Class UsersController
 * @package app\controllers
 */
class SubscribersController extends \yii\web\Controller
{
    public $layout = 'business';
	/**
	 * @param \yii\base\Action $action
	 *
	 * @return bool|void
	 * @throws \yii\web\BadRequestHttpException
	 */
	public function beforeAction( $action )
	{
		if ( \Yii::$app->getUser()->isGuest ) {
			return \Yii::$app->getResponse()->redirect( \yii\helpers\Url::to(['/']) )->send();
		}
		return parent::beforeAction( $action ); // TODO: Change the autogenerated stub
	}

	/**
	 * @return array
	 */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => \yii\filters\AccessControl::className(),
                // We will override the default rule config with the new AccessRule class
                'ruleConfig' => [
                    'class' => AccessRule::className(),
                ],
                'only' => ['index','create', 'update', 'delete'],
                'rules' => [
        
                    [
                        'allow' => true,
                        'actions' => ['index','create', 'update', 'delete'],
                        // admins to create
                        'roles' => [
                               User::ROLE_ADMIN
                        ],
                    ],
                ],
                'denyCallback' => function($rule, $action) {
                    //redirection here
                    return Yii::$app->getResponse()->redirect(['/site/admin']);
               }
            ],
        ];
    }

	/**
	 * @param array $params
	 *
	 * @return $this
	 */
	public function setViewParams(array $params = [])
	{
		$this->view->params = ArrayHelper::merge($this->view->params, $params);
		return $this;
	}

	/**
	 * @return string
	 */
    public function actionIndex()
    {
        $searchModel = new SubscribersSearch();
        $dataProvider = $searchModel->search(\Yii::$app->getRequest()->queryParams);
        $dataProvider->pagination->pageSize=10;

	    \Yii::$app->view->title = \Yii::t('app', 'Users');

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

	/**
    * Export action.
    *
    * @return Response|string
    */
    public function actionExport() {
        $searchModel = new SubscribersSearch();
        $dataProvider = $searchModel->search(\Yii::$app->getRequest()->queryParams);
         $exporter = new CsvGrid([
           'dataProvider' => $dataProvider,
           'columns' => [
               'id',
               'email',
               'phonenumber',
               'status',
               'created',
           ]
           ]);
    
            $time = (int) round(microtime(true) * 1000);
            $exporter->export()->send("subscribers-{$time}.csv");
        }

	/**
	 * @param $id
	 *
	 * @return string|\yii\web\Response
	 * @throws NotFoundHttpException
	 */
   


	/**
	 * @param $id
	 *
	 * @return User|null
	 * @throws NotFoundHttpException
	 */
    protected function findModel($id)
    {
        if (($model = User::findOne($id)) !== null) {
            return $model;
        }
        throw new NotFoundHttpException('The requested page does not exist.');
    }
}
